apiVersion: v1
kind: ConfigMap
metadata:
  name: acs-config
  labels:
    app: acs
data:
  CLOUDDEFENSE_CRYPT_ALGORITHM: AES
  SAME_SITE: None
  SECURE: "true"
  SERVLET_CONTEXT_PATH: ""
  AUTH_DEPLOYMENT_MODE_DOCKER: "true"
  DATASOURCE_NAME: acs
  DATASOURCE_URL: "jdbc:postgresql://db:5432/acs?currentSchema=public,aws,gcp,azure,git,steampipe,performance"
  #DATASOURCE_URL: "jdbc:postgresql://db:5432/{{ .Values.acs.db.name }}?currentSchema=public,aws,gcp,azure,git,steampipe,performance"
  DATASOURCE_USERNAME: admin
  STEAMPIPE_URL: "jdbc:postgresql://localhost:9193/steampipe?currentSchema="
  STEAMPIPE_USERNAME: "steampipe"
  SERVER_USERNAME: "cdefense"
  # FRONTEND_ADDRESS: "https://acs-{{ .Values.hostname }}"
  # BACKEND_ADDRESS: "https://acs-backend-{{ .Values.hostname }}"
  REGION_STATIC: "us-east-1"
  # DEFAULT_FROM_EMAIL: "communication@clouddefense.ai"
  # SMTP_HOST: "smtp.gmail.com"
  # SMTP_USERNAME: "communication@clouddefense.ai"
  HIKARI_MAX_POOL_SIZE: "10"
  SENTRY_ENVIRONMENT: develop
  ROOT_PATH: "/home/steampipe"
  # ASSET_SCAN_K8_NAMESPACE: "dev"
  # ASSET_SCAN_DOCKER_IMAGE_NAME: "cdefense/aws-assets-scan-job:latest"
  IS_K8_ASSET_SCAN_ENABLED: "true"
  DOMAIN: "clouddefenseai.com"
  # NOVELTY_URL: "https://novelty-backend-{{ .Values.hostname }}"
  FRONTEND_SENTRY_DSN: https://804a9e43e9bd4d99a4c5ad4d31650cb4@o1164134.ingest.sentry.io/4504070799425536
  BACKEND_SENTRY_DSN: https://6159ae18a41049ec90c3acce9dfc671e@o1164134.ingest.sentry.io/4504070797918208
  ASSET_SCAN_SENTRY_DSN: https://317433944b444c2eaab7e26d2a643752@o1164134.ingest.sentry.io/4504070800605184
  CLOUDDEFENSE_CRYPT_BASE_SECRET: c6q4yZLkuflZZx80aIHzmlDAn0By66Dg
  CLOUDDEFENSE_ENVIRONMENT: development
  VOLUME_BASE_ADDRESS: "/home/server/data"
  PYTHON_NOVELTY_SCRIPT: "cdefense/python_novelty_script"
  AWS_S3_BUCKET: "asset-scan-job"
  AWS_S3_REGION: "us-west-2"
  # NEW_RELIC_APP_NAME: cloudsec-staging
  BOOTSTRAP_COMPLIANCE_WRITE_FROM_JSON_FILE: "false"