apiVersion: v1
kind: Service
metadata:
  name: acs-backend
  labels:
    app: acs-backend
spec:
  type: NodePort
  selector:
    app: acs-backend
  ports:
    - name: http
      port: 80
      targetPort: 8080